apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
stringData:
  GITHUB_WEBHOOK_SECRET: "myWebhookSecret_abc123XYZ789"
  GITHUB_APP_ID: "3985852"
  GITHUB_APP_PRIVATE_KEY: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEogIBAAKCAQEA6MORI4pR/96P5aDV2AitLV4pGPTpWSO36vxrSxsZfDj+tScf
    h9shfmpGe6qzPIH2Z4WZCp61ZnBtg6xTs7X51r21VwITtLJtpKXs7VoN715NicB0
    +dpJGk5URbgAcChhCGIXxSRUnlX0bpI5cmxCKgYALsEqfZRkCXRr3X/HPZ4nS0H5
    TmvBGKySHGH2O7P8Z464X+54WafmQBYeLRal5bkmgm9DQElqG811cXah1X3mN46T
    AdKsgGocdCVZFk2sfKIPy5j/pdZHXZ0Emc0tpG2uFfJFgzbevNy92ZIIH4+Fxotk
    1PWEjXBJ/V0Txbpw2Q5x/59o9OMoF3f6PhAY7QIDAQABAoIBAFay+a3OSMrQwLKc
    nOqSGMdMSmyUVRKx3kC18tUP7Ac8R4t8Xh9BfRFUTpqjs413LyvSNHYjNZhJilFA
    cBEBWGUnVpNpH6Pvzi1E7KJgJ86gRqtnt2qVZyNYR8WMSwV71ODFgOsapDYx+BDz
    gFhhgKecgpbntob+LeDjr4XaoYEOYOLX7WQ4g9JAJHTLuYGG65GCflIqCX4wWLNf
    fSWBTAAi2KwmPwl7Swux3U/n9TpnhR/oM+FSgA3PXA5SedxyjZquPbmrQgyDsLjI
    w+G5X7NFRNFrATgey5aloVzJXaM4IjpCjuVCKwwHZ6Z4G6OvI3yha3nt7+1BOR5Y
    GItdHSECgYEA9mk5iLjrNnDskWYVUTAubF3Sr3+uA3t9CAtJFVbcI+JuUGjYtxt+
    x1hOrBgow768mb3urpT3coA5QbYG8s54bsGuV9Yjeg7ZEn5Q/srlIskK2i4M3te+
    EwfXChrRXWpLR9RTPcUqxcct1g+4ax1vnaeaYBiYvu2pHK8zeGU1lHkCgYEA8dJj
    YZiuQRyjq3acB1kkgPatyNXCzdEc28FWEv0GrOkzvD0mjdMSonBNXxCSzuOqKKAz
    /jUaYuL4MbceSEHEYJubl2hrJzACPOPP0TiM783WSh6T23vproGnfyM4vUj4DHbJ
    6Ss8aVLdlL5hZ3DBS7EtLRotenTzkUeDo/z5gxUCgYAFp6SKXrQHK9BCBfW3R0PJ
    eN286VE1A0B7Tsb+ll+28xtU/RL8IMVoDb7AdE17MIVjgdhYaVLEbezidSrzp4lc
    AVXe7isiQfT5V6zELCPWCIcXOrdQ5eKWzTdCJBtp6WaQ326JnFy+7TNAFlxFGQfW
    tmH0kpvuxcV7wwmLWcdBAQKBgH/DyuJLyvV37jmvhyySuqiwrI0J88zOiVLKSXHq
    4dYFuGHiZTZVqOjOMPLjTM2ml8azLgVHhVNt2/hYadV/egQY8xICB2tDAEuviaNf
    H4er12Z91V0HkSW0Nw0DTP0lSnk7Yd6iC18SeyQVml0Ow/H8AIRt6k1i8TV29WR1
    SlcpAoGALL77a7cTzHO3MdV79tX8D5Y1wknaSHPXtWKtLll3MCNanyIg1hh39IO4
    yK/lK8GDD20azqNeYzxz/hbdjldjIBL87bTkKHZ6MFnez3gWIMrlp33UQgkvPTVS
    XxLPJeIXVQ/3sNzxYLYFPfT/Uhrkg6jcHFIwWCpDbChtW4YS0rg=
    -----END RSA PRIVATE KEY-----
  OPENAI_API_KEY: "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"
  LANGFUSE_PUBLIC_KEY: "pk-lf-d3c582b1-f28d-4949-8fb5-de607dd18d4b"
  LANGFUSE_SECRET_KEY: "sk-lf-cee5af58-bacb-414f-bd30-cb81bc6fefa0"
  DATABASE_URL: "postgresql+asyncpg://dbadmin:YourStrongPassword123!@ai-code-reviewer-postgres.cqx8w6m0cwaj.us-east-1.rds.amazonaws.com/codereviewer"
